backend:
  name: git-gateway
  branch: main

media_folder: public/library
public_folder: /library

collections:
  - label: Tracks
    name: tracks
    folder: public/library
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: text, required: false}
      - {label: Language, name: language, widget: select, options: [{label: English, value: en}, {label: German, value: de}, {label: فارسی, value: fa}], default: en}
      - {label: Tags, name: tags, widget: list, required: false}
      - {label: Hero Image, name: hero_image, widget: image, required: false}
      - {label: Draft, name: draft, widget: boolean, required: false}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}