backend:
  name: git-gateway
  branch: main

media_folder: public/library
public_folder: /library

collections:
  - label: Music Library
    name: library
    file: public/library.json
    - label: Tracks
      name: tracks
      widget: list
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Artist, name: artist, widget: string}
        - {label: Album, name: album, widget: string}
        - {label: Cover, name: cover_image, widget: image, required: false}
        - {label: Audio, name: audio_file, widget: file, required: false}
        - {label: Description, name: description, widget: markdown}
        - {label: Date, name: date, widget: datetime}
        - {label: Tags, name: tags, widget: list, required: false}